# Generated by Django 4.0 on 2022-03-19 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='model',
            new_name='car_model',
        ),
    ]
