# Generated by Django 4.0 on 2022-03-28 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_brand_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car_model',
            old_name='brand',
            new_name='manufacture',
        ),
        migrations.AddField(
            model_name='brand',
            name='cars_to_brand',
            field=models.ManyToManyField(to='cars.car_model'),
        ),
    ]
