# Generated by Django 4.0 on 2022-03-28 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_rename_brand_car_model_manufacture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_model',
            name='price',
            field=models.IntegerField(default=1000),
        ),
    ]
