# Generated by Django 4.0 on 2022-03-28 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_car_model_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_model',
            name='viewed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='brand',
            name='cars_to_brand',
            field=models.ManyToManyField(blank=True, to='cars.car_model'),
        ),
    ]
